image: alpine/edge
packages:
  - hugo
  - rsync
secrets:
  - 4848e524-dbed-4d6e-b12d-68b4a5a591ba
environment:
  deploy: build@alias-asso.fr
tasks:
  - build: |
      cd alias-asso.fr
      hugo
  - deploy: |
      cd alias-asso.fr
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avh --delete public/ $deploy:/var/www/alias-asso.fr/
